/**
 * Host API version and capability tokens (PG-AGENT-PLAN).
 */

export const HOST_API_VERSION = "1";

/** Capability names returned by HOST.capabilities(). */
export const HOST_CAPABILITIES = [
  "apiVersion",
  "capabilities",
  "listProjects",
  "getProject",
  "createProject",
  "cloneProject",
  "setWorkingSet",
  "deleteProject",
  "openProject",
  "getActiveAgent",
  "setActiveAgent",
  "getTargetProject",
  "setTargetProject",
  "grantSandboxAccess",
  "listFiles",
  "listDir",
  "readFile",
  "writeFile",
  "mkdir",
  "remove",
  "reloadCanvas",
  "getConsole",
  "clearConsole",
  "waitConsole",
  "getCanvasStatus",
  "getNetworkLog",
  "clearNetworkLog",
  "getDomSnapshot",
  "runPython",
  "runCmd",
  "listCmds",
  "readFileBase64",
  "writeFileBase64",
  "openFile",
  "openTool",
  "closeTool",
  "getToolSession",
  "mainTabs",
  "openMainCanvas",
  "closeMainTab",
  "setMainTab",
  "listMainTabs",
  "getMainTab",
  "openSession",
  "closeSession",
  "pauseSession",
  "resumeSession",
  "getSession",
  "listSeats",
  "joinSeat",
  "leaveSeat",
  "spawnParticipant",
  "hostSessionFetch",
  "captureCanvas",
  "listSecretNames",
  "getSecretStoreStatus",
  "listSecrets",
  "createPlatformInvite",
  "revokePlatformInvite",
  "search",
  "expectedHash",
  "checkpoint",
  "restore",
  "listCheckpoints",
  "agentMailbox",
  "agentLeader",
  "agentRegistry",
  "listFleetSummary",
  "getAgentUi",
  "setAgentUi",
] as const;

export type HostCapability = (typeof HOST_CAPABILITIES)[number];
